FROM php:8.2.4-fpm

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    zip \
    unzip \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install pdo_pgsql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

WORKDIR /var/www/Whisper

COPY composer.json composer.lock /var/www/Whisper/

RUN composer install --no-scripts

COPY . /var/

RUN chown -R www-data:www-data /var/www/Whisper/storage /var/www/Whisper/bootstrap/cache

CMD ["php-fpm"]
